server.port : 8089

socketServer:
  address: 192.168.220.79
  port: 8005
apiServer:
  address: 52.79.78.191
  port: 9010
bizServer:
  address: 127.0.0.1
  port: 8090

logging:
  #pattern:
  #file: "%d %-5level [%thread] %logger.%method:%line : %msg%n"
  #file:
    #name: ./logs/biz/biz.log
  level:
    root: debug
    com.chargev: debug
    sun.rmi: info
    javax.management: info
    com.couchbase: info
    org.apache: info
    org.hibernate: info
    org.springframework: info
  logback:
    rollingpolicy:
      max-file-size: 500MB
      max-history: 10